steps:
    #Build the container image - gcloud
    - name: "gcr.io/cloud-builders/gcloud"
      id: "Build"
      entrypoint: gcloud
      args:
          [
              "builds",
              "submit",
              "--pack",
              "image=${_REGION}-docker.pkg.dev/homespace-digital/containers/${_DJANGO_SERVICE_NAME}:$COMMIT_SHA",
              ".",
          ]

    # # Update pip dependencies
    # - name: python
    #   id: "Update pip Dependencies - python"
    #   entrypoint: pip
    #   args: ["install", "--upgrade", "pip"]

    # # Install dependencies
    # - name: python
    #   id: "Install Dependencies - python"
    #   entrypoint: pip
    #   args: ["install", "-r", "requirements.txt", "--user"]

    # #Run Unit tests
    # - name: "python"
    #   id: "Run Unit Tests"
    #   entrypoint: python
    #   args: ["manage.py", "test"]

    # Make Migrations Job
    # - name: "gcr.io/cloud-builders/gcloud"
    #   id: "Makemigrations"
    #   entrypoint: gcloud
    #   args:
    #       - "run"
    #       - "jobs"
    #       - "execute"
    #       - "makemigrations"
    #       - "--region"
    #       - "${_REGION}"
    #       - "--wait"

    #Update Migrate Job
    - name: "gcr.io/cloud-builders/gcloud"
      id: "Update Migrate Job"
      entrypoint: gcloud
      args:
          - "run"
          - "jobs"
          - "update"
          - "migrate"
          - "--region"
          - "${_REGION}"
          - "--image"
          - "${_REGION}-docker.pkg.dev/homespace-digital/containers/${_DJANGO_SERVICE_NAME}:$COMMIT_SHA"

    # Migrate Django models to Cloud SQL
    - name: "gcr.io/cloud-builders/gcloud"
      id: "Migrate"
      entrypoint: gcloud
      args:
          - "run"
          - "jobs"
          - "execute"
          - "migrate"
          - "--region"
          - "${_REGION}"
          - "--wait"

    # Deploy container image to Cloud Run
    - name: "gcr.io/cloud-builders/gcloud"
      id: "Deploy"
      entrypoint: gcloud
      args:
          - "run"
          - "deploy"
          - "${_DJANGO_SERVICE_NAME}"
          - "--region"
          - "${_REGION}"
          - "--image"
          - "${_REGION}-docker.pkg.dev/homespace-digital/containers/${_DJANGO_SERVICE_NAME}:$COMMIT_SHA"
          - "--set-cloudsql-instances"
          - "${_CLOUD_SQL_INSTANCE}"
          - "--set-secrets"
          - "APPLICATION_SETTINGS=application_settings:latest"
          - "--set-secrets"
          - "SERVICE_ACCOUNT=SERVICE_ACCOUNT:latest"
          - "--set-secrets"
          - "MAILERSEND_API_KEY=MAILERSEND_API_KEY:latest"
          - "--service-account"
          - "${_SERVICE_ACCOUNT}"
          - "--allow-unauthenticated"
