# Generated by Django 4.2.10 on 2024-12-07 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
