# Generated by Django 4.2.10 on 2024-12-07 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='amassed_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
