# Generated by Django 4.2.10 on 2024-12-07 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_customuser_amassed_points_customuser_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Descrição')),
                ('points', models.PositiveSmallIntegerField(default=0, verbose_name='Pontos')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Concluída')),
                ('target_date', models.DateField(verbose_name='Data Alvo')),
                ('fk_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Missão Diária',
                'verbose_name_plural': 'Missões Diárias',
            },
        ),
    ]
