# Generated by Django 4.2.10 on 2024-12-11 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_storeitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeitem',
            name='cost',
            field=models.PositiveIntegerField(verbose_name='Custo'),
        ),
        migrations.AlterField(
            model_name='storeitem',
            name='image',
            field=models.CharField(max_length=100, verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='storeitem',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
    ]
