# Generated by Django 4.2.10 on 2024-12-11 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_storeitem_cost_alter_storeitem_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storeitem',
            options={'verbose_name': 'Item da Loja', 'verbose_name_plural': 'Itens da Loja'},
        ),
    ]
