# Generated by Django 4.2.10 on 2024-12-17 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_amassed_points_customuser_amassed_coins_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Conquista')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('target_points', models.PositiveIntegerField(verbose_name='Pontos Alvo')),
                ('image', models.CharField(max_length=100, verbose_name='Imagem')),
                ('unlocked_message', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mensagem Desbloqueada')),
                ('is_secret', models.BooleanField(default=True, verbose_name='Secreto')),
            ],
            options={
                'verbose_name': 'Conquista',
                'verbose_name_plural': 'Conquistas',
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.PositiveIntegerField(default=0, verbose_name='Progresso')),
                ('is_claimed', models.BooleanField(default=False, verbose_name='Resgatado')),
                ('fk_achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conquista do Usuário',
                'verbose_name_plural': 'Conquistas dos Usuários',
                'unique_together': {('user', 'fk_achievement')},
            },
        ),
    ]
